from app.models import db, book_tag, Tag, Book, environment, SCHEMA

def seed_book_tags():
    first_book = Book.query.get(1)
    second_book = Book.query.get(2)
    third_book = Book.query.get(3)
    fourth_book = Book.query.get(4)
    fifth_book = Book.query.get(5)
    sixth_book = Book.query.get(6)
    seventh_book = Book.query.get(7)
    eighth_book = Book.query.get(8)
    ninth_book = Book.query.get(9)
    tenth_book = Book.query.get(10)
    eleventh_book = Book.query.get(11)
    twelfth_book = Book.query.get(12)
    thirteenth_book = Book.query.get(13)
    fourteenth_book = Book.query.get(14)
    fifteenth_book = Book.query.get(15)

    fantasy = Tag.query.get(1)
    realistic = Tag.query.get(2)
    scifi = Tag.query.get(3)
    nonfiction = Tag.query.get(4)
    readaloud = Tag.query.get(5)
    adventure = Tag.query.get(6)
    reluctant = Tag.query.get(7)
    beginning = Tag.query.get(8)
    wordless = Tag.query.get(9)

    fantasy.books.append(first_book)
    fantasy.books.append(second_book)
    fantasy.books.append(fifth_book)
    fantasy.books.append(eighth_book)
    fantasy.books.append(eleventh_book)
    fantasy.books.append(fifteenth_book)
    fantasy.books.append(fourteenth_book)
    realistic.books.append(third_book)
    realistic.books.append(fourth_book)
    realistic.books.append(ninth_book)
    realistic.books.append(twelfth_book)
    realistic.books.append(thirteenth_book)
    scifi.books.append(seventh_book)
    readaloud.books.append(ninth_book)
    readaloud.books.append(fourteenth_book)
    readaloud.books.append(third_book)
    readaloud.books.append(eleventh_book)
    readaloud.books.append(fourth_book)
    adventure.books.append(fourth_book)
    adventure.books.append(fourteenth_book)
    adventure.books.append(tenth_book)
    adventure.books.append(ninth_book)
    reluctant.books.append(ninth_book)
    reluctant.books.append(tenth_book)
    reluctant.books.append(fourth_book)
    beginning.books.append(first_book)
    beginning.books.append(second_book)
    beginning.books.append(sixth_book)
    beginning.books.append(seventh_book)
    wordless.books.append(sixth_book)
    wordless.books.append(seventh_book)
    db.session.commit()

def undo_book_tags():

    if environment == "production":
        db.session.execute(f"TRUNCATE table {SCHEMA}.book_tag RESTART IDENTITY CASCADE;")
    else:
        db.session.execute("DELETE FROM book_tag")

    db.session.commit()