from app.models import db, book_shelf, Shelf, Book, environment, SCHEMA


first_book = Book.query.get(1)
second_book = Book.query.get(2)
third_book = Book.query.get(3)
fourth_book = Book.query.get(4)
fifth_book = Book.query.get(5)
sixth_book = Book.query.get(6)
seventh_book = Book.query.get(7)
eighth_book = Book.query.get(8)
ninth_book = Book.query.get(9)
tenth_book = Book.query.get(10)
eleventh_book = Book.query.get(11)
twelfth_book = Book.query.get(12)
thirteenth_book = Book.query.get(13)
fourteenth_book = Book.query.get(14)
fifteenth_book = Book.query.get(15)
kids = Shelf.query.get(1)
wordless = Shelf.query.get(2)
thinkers = Shelf.query.get(3)
animals = Shelf.query.get(4)

kids.shelves.appends(first_book)
kids.shelves.appends(second_book)
kids.shelves.appends(sixth_book)
kids.shelves.appends(seventh_book)
kids.shelves.appends(eleventh_book)
kids.shelves.appends(fifteenth_book)
wordless.shelves.appends(sixth_book)
wordless.shelves.appends(seventh_book)
thinkers.shelves.appends(third_book)
thinkers.shelves.appends(fourth_book)
thinkers.shelves.appends(fifth_book)
thinkers.shelves.appends(eighth_book)
thinkers.shelves.appends(thirteenth_book)
thinkers.shelves.appends(fourteenth_book)
animals.shelves.appends(first_book)
animals.shelves.appends(second_book)
animals.shelves.appends(eighth_book)
animals.shelves.appends(ninth_book)
animals.shelves.appends(tenth_book)
animals.shelves.appends(eleventh_book)
animals.shelves.appends(twelfth_book)